### PR TITLE
fix: update SOLO_CHART_VERSION to 0.54.3 to use solo-cheetah

### LINKED ISSUE #2047: switch to solo-cheetah from mirror.py by upgrading to solo chart v0.54.2

### PR DESCRIPTION
**Pull request by jeromy-cannon**
## Description

This pull request changes the following:

* update SOLO_CHART_VERSION to 0.54.3 to use solo-cheetah instead of mirror.py for uploading files to the cloud from consensus node
* pass bucket configuration values as string to handle scenario where bucket prefix could be a number (as it is used in gcs_test)

This pull request includes updates to workflows, scripts, configuration files, and versioning. The changes focus on improving error handling, adding new test matrix configurations, updating endpoint URLs, modifying deployment commands, and bumping version numbers for dependencies.

### Workflow Improvements:
* [`.github/workflows/flow-gcs-test.yaml`](diffhunk://#diff-ace6fa1c3b0eccf534e8f0a7b9c6da5458d0ba2ca6ced6fd1ab78e7992f4e7e1L128-R141): Enhanced error handling for the GCS test script by capturing exit codes, running additional solo-test commands on failure, and uploading logs as artifacts.
* [`.github/workflows/flow-migration-test.yaml`](diffhunk://#diff-2a6221a06ab3fe54f6840b05f154fb20e680c006ed218236c734b58e52c38b4dL82-R95): Added a timeout to the network launch script, improved error handling, and included log uploads on failure.

### Script Updates:
* [`.github/workflows/script/gcs_test.sh`](diffhunk://#diff-24d2e554fb02d8ed13d1c581bc2e1bdda7c0bd1c32467f2f043b5e6a3d297a97L68-R68): Simplified endpoint URLs for AWS and GCS by removing "https://" prefix. [[1]](diffhunk://#diff-24d2e554fb02d8ed13d1c581bc2e1bdda7c0bd1c32467f2f043b5e6a3d297a97L68-R68) [[2]](diffhunk://#diff-24d2e554fb02d8ed13d1c581bc2e1bdda7c0bd1c32467f2f043b5e6a3d297a97L82-R82)

### Configuration Changes:
* [`.github/workflows/support/e2e-test-matrix.json`](diffhunk://#diff-06d1f6d94bd04b07253641bf29e3069d881b24256b7cf393e4a39660955e9f3dR2-R8): Re-added the "External database" test configuration with its associated script and coverage report details. [[1]](diffhunk://#diff-06d1f6d94bd04b07253641bf29e3069d881b24256b7cf393e4a39660955e9f3dR2-R8) [[2]](diffhunk://#diff-06d1f6d94bd04b07253641bf29e3069d881b24256b7cf393e4a39660955e9f3dL128-L134)

### Deployment Command Fixes:
* [`examples/Taskfile.examples.yml`](diffhunk://#diff-78204656ee2b0db49dc22e6e5c1efc85cbee56b1f6e7d74ce7e21dd9521f9e68L234-R234): Fixed syntax issues in deployment creation commands and port-forward cleanup logic. [[1]](diffhunk://#diff-78204656ee2b0db49dc22e6e5c1efc85cbee56b1f6e7d74ce7e21dd9521f9e68L234-R234) [[2]](diffhunk://#diff-78204656ee2b0db49dc22e6e5c1efc85cbee56b1f6e7d74ce7e21dd9521f9e68L411-R411)

### Version Updates:
* [`version.ts`](diffhunk://#diff-9840df415b2e8f8effbd38bf4c4cefaa5f691dcc8d6585c41fbcf84a167e6226L15-R15): Updated `SOLO_CHART_VERSION` to `0.54.3` from `0.53.0`.

### Related Issues

* Closes #2047
* Related to #

### Pull request (PR) checklist

* \[ ] This PR added tests (unit, integration, and/or end-to-end)
* \[ ] This PR updated documentation
* \[ ] This PR added no TODOs or commented out code
* \[ ] This PR has no breaking changes
* \[ ] Any technical debt has been documented as a separate issue and linked to this PR
* \[ ] Any `package.json` changes have been explained to and approved by a repository manager
* \[ ] All related issues have been linked to this PR
* \[ ] All changes in this PR are included in the description
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been followed

### Testing

* \[ ] This PR added unit tests
* \[ ] This PR added integration/end-to-end tests
* \[ ] These changes required manual testing that is documented below
* \[ ] Anything not tested is documented

The following manual testing was done:

* TBD

The following was not tested:

* TBD

<details>
<summary>
Commit message guidelines
</summary>
We use 'Conventional Commits' to ensure that our commit messages are easy to read, follow a consistent format, and for automated release note generation. Please follow the guidelines below when writing your commit messages:

1. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.  NOTE: currently breaking changes will only bump the MAJOR version.
2. The title is prefixed with one of the following:

| Prefix    | Description                                         | Semantic Version Update | Captured in Release Notes |
|-----------|-----------------------------------------------------|-------------------------|---------------------------|
| feat:     | a new feature                                       | MINOR                   | Yes                       |
| fix:      | a bug fix                                           | PATCH                   | Yes                       |
| perf:     | performance                                         | PATCH                   | Yes                       |
| refactor: | code change that isn't feature or fix               | none                    | No                        |
| test:     | adding missing tests                                | none                    | No                        |
| docs:     | changes to documentation                            | none                    | Yes                        |
| build:    | changes to build process                            | none                    | No                        |
| ci:       | changes to CI configuration                         | none                    | No                        |
| style:    | formatting, missing semi-colons, etc                | none                    | No                        |
| chore:    | updating grunt tasks etc; no production code change | none                    | No                        |

</details>

### CODE REVIEW

File: version.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ import fs from 'node:fs';
 // TODO we should be consistent on the versioning format, let us drop the v prefix from the user, and manually add it
 //  right before it required, this adds better semver library compatibility
 export const HELM_VERSION: string = 'v3.14.2';
-export const SOLO_CHART_VERSION: string = '0.53.0';
+export const SOLO_CHART_VERSION: string = '0.54.0';
```
Comment (jeromy-cannon) [inline version.ts:15]:
```suggestion
export const SOLO_CHART_VERSION: string = '0.54.1';
```

**Review by nathanklick — APPROVED** [review]
