### PR TITLE
fix: check upgrade package before perform upgrade

### LINKED ISSUE #2151: should check upgrade package exist or not before proceeding with upgrade
### Describe the bug

If user input wrong upgrade version, and the package does not exist,
solo would throw exception but the consensus network already stopped before the error,
the the following solo command may fail since it could not ping consensus node.

### Describe the expected behavior

Should check existence of package first

### To Reproduce

`solo node upgrade --deployment solo-deployment --upgrade-version 0.61.8`

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

*check upgrade package before proceed

### Related Issues

* Closes #2151

### Pull request (PR) checklist

* \[ ] This PR added tests (unit, integration, and/or end-to-end)
* \[ ] This PR updated documentation
* \[ ] This PR added no TODOs or commented out code
* \[ ] This PR has no breaking changes
* \[ ] Any technical debt has been documented as a separate issue and linked to this PR
* \[ ] Any `package.json` changes have been explained to and approved by a repository manager
* \[ ] All related issues have been linked to this PR
* \[ ] All changes in this PR are included in the description
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been followed

### Testing

* \[ ] This PR added unit tests
* \[ ] This PR added integration/end-to-end tests
* \[ ] These changes required manual testing that is documented below
* \[ ] Anything not tested is documented

The following manual testing was done:

* TBD

The following was not tested:

* TBD

<details>
<summary>
Commit message guidelines
</summary>
We use 'Conventional Commits' to ensure that our commit messages are easy to read, follow a consistent format, and for automated release note generation. Please follow the guidelines below when writing your commit messages:

1. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.  NOTE: currently breaking changes will only bump the MAJOR version.
2. The title is prefixed with one of the following:

| Prefix    | Description                                         | Semantic Version Update | Captured in Release Notes |
|-----------|-----------------------------------------------------|-------------------------|---------------------------|
| feat:     | a new feature                                       | MINOR                   | Yes                       |
| fix:      | a bug fix                                           | PATCH                   | Yes                       |
| perf:     | performance                                         | PATCH                   | Yes                       |
| refactor: | code change that isn't feature or fix               | none                    | No                        |
| test:     | adding missing tests                                | none                    | No                        |
| docs:     | changes to documentation                            | none                    | Yes                        |
| build:    | changes to build process                            | none                    | No                        |
| ci:       | changes to CI configuration                         | none                    | No                        |
| style:    | formatting, missing semi-colons, etc                | none                    | No                        |
| chore:    | updating grunt tasks etc; no production code change | none                    | No                        |

</details>

### CODE REVIEW

File: src/commands/node/configs.ts [hunk 1]
```diff
@@ -181,6 +181,27 @@ export class NodeCommandConfigs {
...
+    if (context_.config.upgradeVersion) {
+      const versionPrefix: string = context_.config.upgradeVersion.split('.').slice(0, 2).join('.');
+      const HEDERA_BUILDS_URL: string = 'https://builds.hedera.com';
+      const BUILD_ZIP_URL: string = `${HEDERA_BUILDS_URL}/node/software/${versionPrefix}/build-${context_.config.upgradeVersion}.zip`;
+      try {
+        // do not fetch or download, ust check if URL exists or not
+        const response = await fetch(BUILD_ZIP_URL, {
+          method: 'HEAD',
+          headers: {
+            'User-Agent': 'Solo CLI',
```
Comment (jeromy-cannon) [inline src/commands/node/configs.ts:194]: we should make 'Solo CLI' a constant, we may need this header in other calls in the future.

File: src/commands/node/configs.ts [hunk 2]
```diff
@@ -181,6 +181,27 @@ export class NodeCommandConfigs {
       this.configManager,
     );
 
+    // check if the intended package version exists
+    if (context_.config.upgradeVersion) {
+      const versionPrefix: string = context_.config.upgradeVersion.split('.').slice(0, 2).join('.');
+      const HEDERA_BUILDS_URL: string = 'https://builds.hedera.com';
+      const BUILD_ZIP_URL: string = `${HEDERA_BUILDS_URL}/node/software/${versionPrefix}/build-${context_.config.upgradeVersion}.zip`;
+      try {
+        // do not fetch or download, ust check if URL exists or not
```
Comment (jeromy-cannon) [inline src/commands/node/configs.ts:190]:
```suggestion
        // do not fetch or download, just check if URL exists or not
```

File: src/commands/node/configs.ts [hunk 3]
```diff
@@ -181,6 +181,27 @@ export class NodeCommandConfigs {
       this.configManager,
     );
 
+    // check if the intended package version exists
+    if (context_.config.upgradeVersion) {
+      const versionPrefix: string = context_.config.upgradeVersion.split('.').slice(0, 2).join('.');
```
Comment (jeromy-cannon) [inline src/commands/node/configs.ts:186]: I would just do a new Semver, it will also validate that it is well formed.

File: src/commands/node/configs.ts [hunk 4]
```diff
@@ -181,6 +181,27 @@ export class NodeCommandConfigs {
...
+      const HEDERA_BUILDS_URL: string = 'https://builds.hedera.com';
+      const BUILD_ZIP_URL: string = `${HEDERA_BUILDS_URL}/node/software/${versionPrefix}/build-${context_.config.upgradeVersion}.zip`;
```
Comment (jeromy-cannon) [inline src/commands/node/configs.ts:188]: when you switch to semver, you might need to prefix with a `v` or add some option to get Semver to return it that way

File: src/commands/node/configs.ts (hunk 1 above)
Comment (JeffreyDallas) [reply src/commands/node/configs.ts:194]: Updated

File: src/commands/node/configs.ts (hunk 3 above)
Comment (JeffreyDallas) [reply src/commands/node/configs.ts]: Updated with SemVer

File: src/commands/node/configs.ts (hunk 4 above)
Comment (JeffreyDallas) [reply src/commands/node/configs.ts]: Updated with SemVer

**Review by jeromy-cannon — APPROVED** [review]
