### PR TITLE
fix: add version string checking

### LINKED ISSUE #2310: bug: for the release tag, if the user passes in a semantically correct version without the `v` prefix, it fails
we need to ensure that anytime a version is passed in by the user, that we either add or remove the 'v' as needed based on whether it is needed for a helm chart, image, or consensus node version.

currently, the following is an example of a failure, where the user supplied the CN 0.62.10, but we should prefix it with a `v` for the URL to work for the download:
```
❯ solo node update -d solo-deployment-9b628d4b --node-alias node1 -t 0.62.10

******************************* Solo *********************************************
Version			: 0.40.1
Kubernetes Context	: kind-solo
Kubernetes Cluster	: kind-solo
Current Command		: node update --deployment solo-deployment-9b628d4b --node-alias node1 --release-tag 0.62.10
**********************************************************************************
✔ Load configuration [0.1s]
✔ Initialize [0.4s]
✔ Validate nodes state node1
✔ Identify existing network nodes
  ✔ Check network pod: node1
✔ Load node admin key
✔ Prepare upgrade zip file for node upgrade process [2s]
✔ Check existing nodes staked amount [2s]
✔ Send node update transaction [2s]
✔ Send prepare upgrade transaction [4s]
✔ Send freeze upgrade transaction [2s]
✔ Check all nodes are FROZEN [9s]
  ✔ Check network pod: node1  - status FREEZE_COMPLETE, attempt: 6/300 [9s]
✔ Download generated files from an existing node [0.5s]
✔ Prepare staging directory
  ✔ Create and populate staging directory
  ✔ Copy Gossip keys to staging
  ✔ Copy gRPC TLS keys to staging
✔ Copy node keys to secrets
  ✔ Copy TLS keys
  ✔ Node: node1, cluster: kind-solo
    ✔ Copy Gossip keys
✔ Get node logs and configs [4s]
↓ Update chart to use new configMap due to account number change
✔ Kill nodes to pick up updated configMaps [2s]
✔ Check node pods are running [10s]
  ✔ Check Node: node1 [10s]
❯ Fetch platform software into network nodes
  ✖ Update node: node1 [ platformVersion = 0.62.10, context = kind-solo ]
◼ Setup network nodes
◼ Starting nodes
◼ Enable port forwarding
◼ Check all nodes are ACTIVE
◼ Check all node proxies are ACTIVE
◼ Trigger stake weight calculate
◼ Finalize

Log file content from /opt/hgcapp/services-hedera/HapiApp2.0/output/extract-platform.log:
2025-07-18 13:46:19 - extract-platform.sh: begin................................
2025-07-18 13:46:19 - Checking if /home/hedera/build-0.62.10.zip exists...
2025-07-18 13:46:19 - Downloading https://builds.hedera.com/node/software/0.62/build-0.62.10.zip...
curl: (22) The requested URL returned error: 404
2025-07-18 13:46:20 - Failed to download https://builds.hedera.com/node/software/0.62/build-0.62.10.zip. Error code: 22
*********************************** ERROR *****************************************
Error in updating nodes: failed to extract platform code in this pod 'solo-9b628d4b/network-node1-0' while using the 'kind-solo' context: execContainer[network-node1-0,607c33e8-730e-4695-955b-d571c4e5792c]: Failure occurred
***********************************************************************************
*********************************** ERROR *****************************************
node update failed: Error in updating nodes: failed to extract platform code in this pod 'solo-9b628d4b/network-node1-0' while using the 'kind-solo' context: execContainer[network-node1-0,607c33e8-730e-4695-955b-d571c4e5792c]: Failure occurred
***********************************************************************************
```

### LINKED ISSUE #2311: bug: cluster-ref connect should be idempotent
if the cluster-ref connect command is ran more than once, it will fail after the first time with an error because the cluster-ref already exists.  If the cluster-ref and the context are the same as what is already in local-config, then it should not error out, but just skip the steps and exit successfully, perhaps displaying a message that the connection already exists in local config.

### PR DESCRIPTION
**Pull request by JeffreyDallas**
## Description

This pull request changes the following:

* Check for releaseTag version
* Show user message instead of throw error if cluster-ref connect is called twice 

### Related Issues

* Closes #2310 
* Closes #2311

### Pull request (PR) checklist

* \[ ] This PR added tests (unit, integration, and/or end-to-end)
* \[ ] This PR updated documentation
* \[ ] This PR added no TODOs or commented out code
* \[ ] This PR has no breaking changes
* \[ ] Any technical debt has been documented as a separate issue and linked to this PR
* \[ ] Any `package.json` changes have been explained to and approved by a repository manager
* \[ ] All related issues have been linked to this PR
* \[ ] All changes in this PR are included in the description
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been followed

### Testing

* \[ ] This PR added unit tests
* \[ ] This PR added integration/end-to-end tests
* \[ ] These changes required manual testing that is documented below
* \[ ] Anything not tested is documented

The following manual testing was done:

* TBD

The following was not tested:

* TBD

<details>
<summary>
Commit message guidelines
</summary>
We use 'Conventional Commits' to ensure that our commit messages are easy to read, follow a consistent format, and for automated release note generation. Please follow the guidelines below when writing your commit messages:

1. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.  NOTE: currently breaking changes will only bump the MAJOR version.
2. The title is prefixed with one of the following:

| Prefix    | Description                                         | Semantic Version Update | Captured in Release Notes |
|-----------|-----------------------------------------------------|-------------------------|---------------------------|
| feat:     | a new feature                                       | MINOR                   | Yes                       |
| fix:      | a bug fix                                           | PATCH                   | Yes                       |
| perf:     | performance                                         | PATCH                   | Yes                       |
| refactor: | code change that isn't feature or fix               | none                    | No                        |
| test:     | adding missing tests                                | none                    | No                        |
| docs:     | changes to documentation                            | none                    | Yes                        |
| build:    | changes to build process                            | none                    | No                        |
| ci:       | changes to CI configuration                         | none                    | No                        |
| style:    | formatting, missing semi-colons, etc                | none                    | No                        |
| chore:    | updating grunt tasks etc; no production code change | none                    | No                        |

</details>

### CODE REVIEW

**Review by jeromy-cannon — CHANGES_REQUESTED** [review]
> we need to ensure that anytime a version is passed in by the user, that we either add or remove the 'v' as needed based on whether it is needed for a helm chart, image, or consensus node version.

I only see the CN version check.  But, I expected to see a check for passing in the helm chart versions as well

**Review by instamenta — APPROVED** [review]

File: src/commands/node/tasks.ts
Comment (jeromy-cannon) [inline src/commands/node/tasks.ts:1]: what about https://github.com/hiero-ledger/solo/blob/0c3e56546fc8ebae28647711ee62c3e94f91e514/src/commands/node/tasks.ts#L2297

File: src/commands/explorer.ts
Comment (jeromy-cannon) [inline src/commands/explorer.ts:1]: what about https://github.com/hiero-ledger/solo/blob/0c3e56546fc8ebae28647711ee62c3e94f91e514/src/commands/explorer.ts#L306

File: src/commands/relay.ts
Comment (jeromy-cannon) [inline src/commands/relay.ts:1]: we should probably update this reference to use the new method for consistency: https://github.com/hiero-ledger/solo/blob/main/src/commands/relay.ts#L163-L164

File: src/business/utils/version.ts [hunk 1]
```diff
@@ -54,3 +57,37 @@ export class Version<T extends SemVer | number> {
...
+ * @param isNeedPrefix - If true, adds 'v' prefix if missing; if false, removes 'v' prefix if present
+ * @param label - Label to use in error messages (e.g., 'Release tag', 'Version')
+ * @returns The processed version string with proper prefix handling
+ * @throws SoloError or IllegalArgumentError if the version string is invalid
+ */
+export function validateSemVer(
+  versionString: string,
+  isNeedPrefix: boolean = false,
+  label: string = 'Version',
+): string {
```
[the remark this answers is not in the document]
Comment (JeffreyDallas) [reply src/business/utils/version.ts]: Changed to static function of Version class

File: src/commands/node/tasks.ts
Comment (JeffreyDallas) [reply src/commands/node/tasks.ts:1]: Added extra checking.

File: src/commands/cluster/tasks.ts
[the remark this answers is not in the document]
Comment (JeffreyDallas) [reply src/commands/cluster/tasks.ts:1]: Added extra checking.

File: src/commands/explorer.ts
Comment (JeffreyDallas) [reply src/commands/explorer.ts:1]: Added extra checking.

**Review by jeromy-cannon — APPROVED** [review]
