### PR TITLE
fix: Improvements to node upgrade e2e tests

### LINKED ISSUE #2046: Create an E2E test that will install with a one version down Consensus Node, and then upgrade to the next minor version up
Create an E2E test that will deploy a network with a Consensus Node version, example being the one that we currently support using version.ts, then upgrade to the next minor version up and store that constant in the version-test.ts.  Eg: install -> v0.60.1, upgrade -> v0.61.7.  

Then verify that the upgrade was successful.  Verification minimum: 
- the network node pods version file shows it is at the new version
- all network pods show as active (using the method that tests the metrics port)
- we can create an account on the ledger
- the account shows up in the explorer

the existing `solo node upgrade` command most likely has bugs.  These notes were captured during a [thread between Nathan, Jeffrey, and I (Jeromy)](https://swirldslabs.slack.com/archives/C081TQ6C7C4/p1743790791568129):

Service code upgrade with / without configuration/settings change:
1. start a network.
2. send freeze transaction (and minimal zip file upload) whether or not there are configuration changes
3. Solo copy files from data/upgrade/current to HapiApp2.0 (similar to NMT would do)
4. Solo fetch new code from registry to HapiApp2.0 data/libs and data/apps
5. start nodes again.

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
## Description

- This PR enhances the existing e2e node upgrade tests by adding additional assertions and test cases, running the upgrade command with and without providing an `upgrade.zip` file.
Fixes an issue where the command would fail if the local `staging` directory does not exist. This can occur when the command is executed on a fresh `solo` installation.

### Related Issues

* Closes #2046 
* Related to #

### Pull request (PR) checklist

* \[ ] This PR added tests (unit, integration, and/or end-to-end)
* \[ ] This PR updated documentation
* \[ ] This PR added no TODOs or commented out code
* \[ ] This PR has no breaking changes
* \[ ] Any technical debt has been documented as a separate issue and linked to this PR
* \[ ] Any `package.json` changes have been explained to and approved by a repository manager
* \[ ] All related issues have been linked to this PR
* \[ ] All changes in this PR are included in the description
* \[ ] When this PR merges the commits will be squashed and the title will be used as the commit message, the 'commit message guidelines' below have been followed

### Testing

* \[ ] This PR added unit tests
* \[ ] This PR added integration/end-to-end tests
* \[ ] These changes required manual testing that is documented below
* \[ ] Anything not tested is documented

The following manual testing was done:

* TBD

The following was not tested:

* TBD

<details>
<summary>
Commit message guidelines
</summary>
We use 'Conventional Commits' to ensure that our commit messages are easy to read, follow a consistent format, and for automated release note generation. Please follow the guidelines below when writing your commit messages:

1. BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.  NOTE: currently breaking changes will only bump the MAJOR version.
2. The title is prefixed with one of the following:

| Prefix    | Description                                         | Semantic Version Update | Captured in Release Notes |
|-----------|-----------------------------------------------------|-------------------------|---------------------------|
| feat:     | a new feature                                       | MINOR                   | Yes                       |
| fix:      | a bug fix                                           | PATCH                   | Yes                       |
| perf:     | performance                                         | PATCH                   | Yes                       |
| refactor: | code change that isn't feature or fix               | none                    | No                        |
| test:     | adding missing tests                                | none                    | No                        |
| docs:     | changes to documentation                            | none                    | Yes                        |
| build:    | changes to build process                            | none                    | No                        |
| ci:       | changes to CI configuration                         | none                    | No                        |
| style:    | formatting, missing semi-colons, etc                | none                    | No                        |
| chore:    | updating grunt tasks etc; no production code change | none                    | No                        |

</details>

### CODE REVIEW

File: src/core/helpers.ts [hunk 1]
```diff
@@ -570,3 +572,17 @@ async function throwAfter(duration: Duration, message: string = 'Timeout'): Prom
...
+): Promise<string> {
+  return k8
+    .containers()
+    .readByRef(ContainerReference.of(podReference, constants.ROOT_CONTAINER))
+    .execContainer([
+      'bash',
+      '-c',
+      String.raw`curl -s http://localhost:9999/metrics | grep platform_PlatformStatus | grep -v \#`,
+    ]);
+}
```
Comment (jeromy-cannon) [inline src/core/helpers.ts:588]: move to: `src/core/network-nodes.ts`

**Review by jeromy-cannon — APPROVED** [review]

**Review by jeromy-cannon — APPROVED** [review]
